import { router } from 'expo-router';
import { Image, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { colors, radius } from '@/lib/theme';
const property=require('../assets/west-plano.jpg');

export default function SellerProfileScreen(){
 const listings=[['West Plano, TX','$610,000'],['Arlington, TX','$485,000'],['Mesquite, TX','$325,000']];
 return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.content}>
  <View style={styles.header}><Pressable onPress={()=>router.back()}><Text style={styles.back}>‹</Text></Pressable><Text style={styles.headerTitle}>Seller profile</Text><Text>•••</Text></View>
  <View style={styles.identity}><View style={styles.avatar}><Text style={styles.initials}>RF</Text></View><View><View style={styles.nameRow}><Text style={styles.name}>Robert Fox</Text><Text style={styles.verified}>✓ Verified Seller</Text></View><Text style={styles.muted}>Licensed Real Estate Agent</Text><Text style={styles.muted}>Fox Premier Realty</Text></View></View>
  <View style={styles.stats}><Stat label="Texas License" value="Active"/><Stat label="Member Since" value="Jan 2018"/><Stat label="Avg. Response" value="Within 2 hours"/><Stat label="Completed Deals" value="128"/></View>
  <Text style={styles.section}>About Robert</Text><Text style={styles.bio}>Local DFW agent focused on verified off-market opportunities and helping serious investors find strong, value-driven deals.</Text>
  <View style={styles.sectionRow}><Text style={styles.section}>Current listings</Text><Text style={styles.link}>View all</Text></View>
  <View style={styles.listings}>{listings.map((item)=><Pressable key={item[0]} style={styles.card} onPress={()=>router.push('/opportunity')}><Image source={property} style={styles.image}/><Text style={styles.cardTitle}>{item[0]}</Text><Text style={styles.cardCopy}>{item[1]}</Text></Pressable>)}</View>
  <Pressable style={styles.primary}><Text style={styles.primaryText}>View listings</Text></Pressable><Pressable style={styles.report}><Text style={styles.reportText}>Report profile</Text></Pressable>
 </ScrollView></SafeAreaView>
}
function Stat({label,value}:{label:string;value:string}){return <View style={styles.stat}><Text style={styles.muted}>{label}</Text><Text style={styles.statValue}>{value}</Text></View>}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:colors.ivory},content:{padding:20,paddingBottom:40},header:{height:48,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},back:{fontSize:36},headerTitle:{fontFamily:'serif',fontSize:20},identity:{flexDirection:'row',gap:13,alignItems:'center',marginTop:10},avatar:{width:62,height:62,borderRadius:31,backgroundColor:colors.emerald,alignItems:'center',justifyContent:'center'},initials:{color:colors.gold,fontWeight:'700',fontSize:19},nameRow:{flexDirection:'row',gap:8,alignItems:'center'},name:{fontSize:18,fontWeight:'700'},verified:{fontSize:9,color:colors.white,backgroundColor:colors.emerald,padding:5,borderRadius:radius.pill,overflow:'hidden'},muted:{color:colors.muted,fontSize:10,marginTop:2},stats:{backgroundColor:colors.white,borderWidth:1,borderColor:colors.border,borderRadius:radius.md,padding:14,marginTop:18,gap:10},stat:{flexDirection:'row',justifyContent:'space-between'},statValue:{fontSize:10,fontWeight:'700'},section:{fontFamily:'serif',fontSize:18,marginTop:20},bio:{fontSize:11,lineHeight:18,color:colors.muted,marginTop:8},sectionRow:{flexDirection:'row',justifyContent:'space-between',alignItems:'flex-end'},link:{color:colors.emerald,fontSize:10},listings:{flexDirection:'row',gap:8,marginTop:10},card:{flex:1,backgroundColor:colors.white,borderRadius:radius.sm,overflow:'hidden'},image:{width:'100%',height:75},cardTitle:{fontSize:9,fontWeight:'700',padding:7,paddingBottom:1},cardCopy:{fontSize:9,color:colors.muted,paddingHorizontal:7,paddingBottom:8},primary:{height:48,backgroundColor:colors.emerald,borderRadius:radius.sm,alignItems:'center',justifyContent:'center',marginTop:24},primaryText:{color:colors.white,fontWeight:'700'},report:{alignItems:'center',padding:16},reportText:{color:colors.muted,fontSize:11}});
